version: "3.8"

services:
  mailer1:
    image: mailing-service
    container_name: mailer1
    # ports:
    #   - "9001:9000"
    env_file:
      - .env

  mailer2:
    image: mailing-service
    container_name: mailer2
    # ports:
    #   - "9002:9000"
    env_file:
      - .env

  mailer3:
    image: mailing-service
    container_name: mailer3
    # ports:
    #   - "9003:9000"
    env_file:
      - .env
  redis:
    image: redis
    container_name: redis_q
    # ports:
    #   - "6379:6379"


  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mailer1
      - mailer2
      - mailer3